server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  zipkin: 
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  application:
    name: api-catalog
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      database: catalog
      port: 27017
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        failureRateThreshold: '40'
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        allowHealthIndicatorToFail: 'false'
        registerHealthIndicator: 'true'
        slidingWindowSize: '10'
        permittedNumberOfCallsInHalfOpenState: '3'
        waitDurationInOpenState: '15000'
      instances:
        series:
          base-config: default
        movies:
          base-config: default
      retry:
        configs:
          default:
            maxAttempts: '3'
            waitDuration: '1000'
            retryExceptions[0]: feign.FeignException$InternalServerError
        instances:
          movies:
            base-config: default
          series:
            base-config: default
