server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
  cloud:
    config:
      enabled: false
  data:
    mongodb:
      database: serie
      port: 27017
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
